[package]
name = "bytecode-verifier"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem bytecode verifier"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
mirai-annotations = "1.10.1"
petgraph = "0.5.1"

borrow-graph = { path = "../borrow-graph" }
move-binary-format = { path = "../move-binary-format" }
move-core-types = { path = "../move-core/types" }

[dev-dependencies]
diem-workspace-hack = { path = "../../common/workspace-hack" }
invalid-mutations = { path = "invalid-mutations" }

[features]
default = []
