[package]
name = "data-streaming-service"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
repository = "https://github.com/diem/diem"
description = "The data streaming service that sends data notifications to clients"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
async-trait = "0.1.42"
futures = "0.3.12"
serde = { version = "1.0.124", default-features = false }
thiserror = "1.0.24"

channel = { path = "../../../common/channel" }
diem-types = { path = "../../../types" }
diem-workspace-hack = { path = "../../../common/workspace-hack" }

[dev-dependencies]
claim = "0.5.0"
