[package]
name = "storage-service-server"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "The Diem storage service (server-side)"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
serde = { version = "1.0.124", default-features = false }
thiserror = "1.0.24"

diem-crypto = { path = "../../../crypto/crypto" }
diem-types = { path = "../../../types" }
diem-workspace-hack = { path = "../../../common/workspace-hack" }
storage-interface = { path = "../../../storage/storage-interface" }
storage-service-types = { path = "../types" }

[dev-dependencies]
anyhow = "1.0.38"
bcs = "0.1.2"
claim = "0.5.0"

diem-crypto = { path = "../../../crypto/crypto" }
diem-types = { path = "../../../types" }
move-core-types = { path = "../../../language/move-core/types" }
storage-interface = { path = "../../../storage/storage-interface" }
