[package]
name = "diem-api-types"
version = "0.0.1"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem API Types"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = ["crates-io"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
hex = "0.4.3"
serde = { version = "1.0.124", default-features = false }
serde_json = "1.0.64"
serde_with = "1.10.0"
warp = { version = "0.3.0", features = ["default"] }

diem-types = { path = "../../types", version = "0.0.2" }

[dev-dependencies]
diem-workspace-hack = { path = "../../common/workspace-hack" }
