[package]
name = "ir-testsuite"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem functional tests"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
diem-workspace-hack = { version = "0.1", path = "../../crates/diem-workspace-hack" }

[dev-dependencies]
anyhow = "1.0.38"
move-bytecode-verifier = { path = "../move-bytecode-verifier" }
datatest-stable = "0.1.1"
functional-tests = { path = "../testing-infra/functional-tests" }
move-ir-to-bytecode = { path = "../move-ir-compiler/move-ir-to-bytecode" }
diem-types = { path = "../../types" }
move-ir-types = { path = "../move-ir/types" }
diem-framework-releases = { path = "../../diem-move/diem-framework/DPN/releases" }
move-binary-format = { path = "../move-binary-format" }
move-core-types = { path = "../move-core/types" }
move-symbol-pool = { path = "../move-symbol-pool" }


[[test]]
name = "testsuite"
harness = false
