[package]
name = "Message"
version = "0.0.0"

[addresses]
# Std = "0x1"
MessageAddress = "0x24163afcc6e33b0a9473852e18327fa9"

[dependencies]
MoveStdlib = { local = "/Users/droc/workspace/diem/language/move-stdlib", addr_subst = { "Std" = "0x1" }}
