[package]
name = "diem-data-client"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "The Diem data client"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
async-trait = "0.1.42"
futures = "0.3.12"
serde = { version = "1.0.124", default-features = false }
thiserror = "1.0.24"

diem-crypto = { path = "../../crypto/crypto" }
diem-types = { path = "../../types" }
diem-workspace-hack = { path = "../../common/workspace-hack" }
storage-service-types = { path = "../storage-service/types" }
