[package]
name = "diemdb-benchmark"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "DiemDb benchmark"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
indicatif = "0.15.0"
itertools = { version = "0.10.0", default-features = false }
structopt = "0.3.21"

executor = { path = "../../execution/executor" }
executor-benchmark = { path = "../../execution/executor-benchmark" }
diemdb = { path = "../diemdb" }
diem-crypto = { path = "../../crypto/crypto" }
diem-genesis-tool = {path = "../../config/management/genesis", features = ["testing"] }
diem-jellyfish-merkle = { path = "../jellyfish-merkle" }
diem-config = { path = "../../config" }
diem-types = { path = "../../types" }
diem-vm= { path = "../../language/diem-vm" }
diem-workspace-hack = { path = "../../common/workspace-hack" }
storage-interface = { path = "../storage-interface" }

[features]
default = []
fuzzing = ["diem-types/fuzzing"]
