[package]
name = "state-sync-multiplexer"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
repository = "https://github.com/diem/diem"
description = "A multiplexer supporting several different state sync versions"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
futures = "0.3.12"

consensus-notifications = { path = "../../../state-sync/inter-component/consensus-notifications" }
diem-config = { path = "../../../config" }
diem-types = { path = "../../../types" }
diem-workspace-hack = { path = "../../../common/workspace-hack" }
event-notifications = { path = "../../../state-sync/inter-component/event-notifications" }
executor-types = { path = "../../../execution/executor-types" }
mempool-notifications = { path = "../../../state-sync/inter-component/mempool-notifications" }
network = { path = "../../../network" }
state-sync-v1 = { path = "../../../state-sync/state-sync-v1" }
storage-interface = { path = "../../../storage/storage-interface" }

[dev-dependencies]
