[package]
name = "framework-releases"
version = "0.1.0"
edition = "2018"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem stdlib"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false

[dependencies]
bytecode-verifier = { path = "../../bytecode-verifier" }
move-lang = { path = "../../move-lang" }
diem-types = { path = "../../../types" }
diem-workspace-hack = { path = "../../../common/workspace-hack" }
move-binary-format = { path = "../../move-binary-format" }
move-core-types = { path = "../../move-core/types" }
move-vm-types = { path = "../../move-vm/types" }
move-vm-runtime = { path = "../../move-vm/runtime" }
move-bytecode-utils = { path = "../../tools/move-bytecode-utils" }
move-command-line-common = { path = "../../move-command-line-common" }
move-package = { path = "../../tools/move-package" }

bcs = "0.1.2"
anyhow = "1.0.38"
clap = "2.33.3"
log = "0.4.14"
rayon = "1.5.0"
sha2 = "0.9.3"
walkdir = "2.3.1"
once_cell = "1.7.2"
smallvec = "1.6.1"
structopt = "0.3.21"
include_dir = "0.6.0"
